### ISSUE TITLE
The share link of "FaceForensics++, DeepfakeDetection, FaceShifter" is invalid.

### ISSUE THREAD

**Issue by WenOOI** [SCLBD/DeepfakeBench#1]
Thanks for your work. It helps a lot. But the share link of Dataset "FaceForensics++, DeepfakeDetection, FaceShifter" doesn't work. 

Could you update the share link?

Thanks!

**Comment by YZY-stack** [comment]
Hi,

I am delighted to hear that our benchmark has been helpful to you and your work. We greatly appreciate your support.

I would like to extend our sincere apologies for the inconvenience caused by the invalid link to the FF++ dataset. We will provide an updated link for the dataset very soon!

Thank you for your understanding and patience. If you have any further questions, please don't hesitate to reach out.

**Comment by lulin60** [comment]
> Thanks for your work. It helps a lot. But the share link of Dataset "FaceForensics++, DeepfakeDetection, FaceShifter" doesn't work.
> 
> Could you update the share link?
> 
> Thanks!

 Do you know what the password in onedrive for downloading is？could you help me ?
