### ISSUE TITLE
 Processed Dataset

### ISSUE THREAD

**Issue by Leesoon1984** [SCLBD/DeepfakeBench#6]
Very outstanding job, can you share the processing data set?

**Comment by YZY-stack** [comment]
Hi,

We appreciate your interest in our work. We understand that the dataset we processed is quite extensive, with each video comprising only 32 frames. In order to cater to your specific requirements more effectively, we highly recommend that you undertake the extraction of video frames yourself prior to training.

Thank you once again for your interest in our project.

Best regards

**Comment by Leesoon1984** [comment]
> Hi,
> 
> We appreciate your interest in our work. We understand that the dataset we processed is quite extensive, with each video comprising only 32 frames. In order to cater to your specific requirements more effectively, we highly recommend that you undertake the extraction of video frames yourself prior to training.
> 
> Thank you once again for your interest in our project.
> 
> Best regards

谢谢答复。
由于实验结果不一致，可能是数据处理的原因，所以希望用处理好的数据进行训练。

**Comment by YZY-stack** [comment]
> > Hi,
> > We appreciate your interest in our work. We understand that the dataset we processed is quite extensive, with each video comprising only 32 frames. In order to cater to your specific requirements more effectively, we highly recommend that you undertake the extraction of video frames yourself prior to training.
> > Thank you once again for your interest in our project.
> > Best regards
> 
> 谢谢答复。 由于实验结果不一致，可能是数据处理的原因，所以希望用处理好的数据进行训练。

hi，我已经上传了我实验所使用的数据。你可以从最新的下载链接下载所有的videos, frames, masks, and landmarks. 谢谢。
